# Generated by Django 3.2.6 on 2023-04-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230412_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='value',
            field=models.TextField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
